### ISSUE TITLE
Cannot unlink ApplicationLinks

### ISSUE THREAD

**Issue by g-luca** [desmos-labs/djuno#8]
## Bug description
After sending a MsgUnlinkApplication djuno doesn’t delete the Application link.

## Steps to reproduce
 

I tried to unlink my Twitch account and the chain deleted correctly the record ( [LCD response](https://lcd.morpheus.desmos.network/desmos/profiles/v1beta1/app-links/desmos16c60y8t8vra27zjg2arlcd58dck9cwn7p6fwtd) ), but when I query Hasura with :
```
profile(where: {dtag: {_ilike: "luca"}}) {
    application_links {
      application
      username
    }
}
```
I still get the Twitch link in the response:
```
...
        },
        {
          "application": "twitch",
          "username": "lucag__"
        },
...

```

**Comment by RiccardoM** [comment]
This should be fixed now. Can you please try linking it again and then de-linking it to make sure? @g-luca

**Comment by g-luca** [comment]
yes, fixed!
